name       : usbredir
version    : 0.8.0
release    : 3
source     :
    - https://gitlab.freedesktop.org/spice/usbredir/uploads/0996a17e5fb99309cfc971e499d036f5/usbredir-0.8.0.tar.bz2 : 87bc9c5a81c982517a1bec70dc8d22e15ae197847643d58f20c0ced3c38c5e00
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : USB redirection protocol
description: |
    usbredir is a protocol for redirection USB traffic from a single USB device, to a different (virtual) machine then the one to which the USB device is attached. See usb-redirection-protocol.txt for the description / definition of this protocol.
optimize   : speed
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
