name       : usbredir
version    : 0.7
release    : 1
source     :
    - http://spice-space.org/download/usbredir/usbredir-0.7.tar.bz2 : 0a63a0712b5dc62be9cca44f97270fea5d1ec1fe7dde0c11dc74a01c8e2006aa
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : USB redirection protocol
description: |
    usbredir is a protocol for redirection USB traffic from a single USB device,
    to a different (virtual) machine then the one to which the USB device is
    attached. See usb-redirection-protocol.txt for the description / definition
    of this protocol.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
