name       : usbredir
version    : 0.12.0
release    : 6
source     :
    - https://gitlab.freedesktop.org/spice/usbredir/-/archive/usbredir-0.12.0/usbredir-usbredir-0.12.0.tar.bz2 : 45a0109191f08e966455ff2ed8f3ce2eb3bee3cbc967ef22b207745c41732ff9
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : USB redirection protocol
description: |
    usbredir is a protocol for redirection USB traffic from a single USB device, to a different (virtual) machine then the one to which the USB device is attached. See usb-redirection-protocol.txt for the description / definition of this protocol.
optimize   : speed
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
