name       : usbredir
version    : 0.13.0
release    : 7
source     :
    - https://gitlab.freedesktop.org/spice/usbredir/-/archive/usbredir-0.13.0/usbredir-usbredir-0.13.0.tar.bz2 : f8281022a7ede923b532dd1f869e5348898d44ccf1ccb4af22e8bf20810d9737
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : USB redirection protocol
description: |
    usbredir is a protocol for redirection USB traffic from a single USB device, to a different (virtual) machine then the one to which the USB device is attached. See usb-redirection-protocol.txt for the description / definition of this protocol.
optimize   : speed
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
