name       : usbredir
version    : 0.7.1
release    : 2
source     :
    - http://www.spice-space.org/download/usbredir/usbredir-0.7.1.tar.bz2 : 407e9e27a1369f01264d5501ffbe88935ddd7d5de675f5835db05dc9c9ac56f3
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : USB redirection protocol
optimize   : speed
component  : desktop.library
description: |
    usbredir is a protocol for redirection USB traffic from a single USB device,
    to a different (virtual) machine then the one to which the USB device is
    attached. See usb-redirection-protocol.txt for the description / definition
    of this protocol.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
